[project]
name = "contain-agent"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yaniv Aknin", email = "yaniv@aknin.name" }
]
requires-python = ">=3.14"
dependencies = [
    "typer>=0.27.1",
]

[project.scripts]
contain-agent = "contain_agent:app"

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.3",
]
